DollorBox/DollorBox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap


# サイトマップ
from .sitemaps import (
    PostSitemap,
    StaticViewSitemap,
)

sitemaps = {
    'post': PostSitemap,
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('kanrisya987123/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('', include('mathQA.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap')
]

DollorBox/mathQA/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = "mathQA"
urlpatterns = [
    path("", views.index, name="index"),
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("user/", views.user, name="user"),
    path("writeQ/", views.writeQ, name="writeQ"),
    path("detail/<int:questionID>/", views.detail, name="detail"),
    path("searchResult/<int:start>/", views.searchResult, name="searchResult"),
    path("undone/", views.undone, name="undone"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("terms_of_service/", views.terms_of_service, name="terms_of_service"),
    path("tutorial/", views.tutorial, name="tutorial"),
    path("adding_tag_request/", views.adding_tag_request, name="adding_tag_request"),
    path(
        "adding_tag_request_post/",
        views.adding_tag_request_post,
        name="adding_tag_request_post",
    ),
    path("opinionaire/", views.opinionaire, name="opinionaire"),
    path("img_post/", views.img_post, name="img_post"),
    path("good_post/", views.good_post, name="good_post"),
    path(
        "settings_post/<str:section>/<str:item>/",
        views.settings_post,
        name="settings_post",
    ),
    path("bestans_post/<int:questionID>/", views.bestans_post, name="bestans_post"),
    path("tags/<str:tag>/<int:start>/", views.searchResult, name="tagSearchResult"),
    path("auth-complete/<str:token>/", views.auth_complete, name="auth-complete"),
    path("landingpage/", views.LandingPage, name="landingpage"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DollorBox/mathQA/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser


class Token(models.Model):
    token = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name_plural = "トークン"


class CustomUser(AbstractUser):
    icon = models.ImageField(upload_to="icon/", default="system_init/firsticon.jpg")
    verified = models.BooleanField(default=False)
    emailtoken = models.OneToOneField(
        Token, on_delete=models.CASCADE, null=True, blank=True
    )

    class Meta:
        verbose_name_plural = "カスタムユーザー"


class QuestionTag(models.Model):
    tagName = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.tagName)

    class Meta:
        ordering = ["-created_at"]
        verbose_name_plural = "使用可能なタグ(追加可能)"


class Question(models.Model):
    title = models.CharField(max_length=200, null=True)
    customUser = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    contents = models.TextField()
    bestAnswer = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(default=timezone.now)
    cntBrowsed = models.PositiveIntegerField(default=0)
    tags = models.ManyToManyField(QuestionTag)

    def __str__(self):
        return self.contents[:15]

    class Meta:
        ordering = ["-updated_at"]
        verbose_name_plural = "質問"


class Answer(models.Model):
    customUser = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    contents = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.question.title

    class Meta:
        ordering = ["updated_at"]
        verbose_name_plural = "解答"


class Reply(models.Model):
    customUser = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    contents = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.answer.question.title

    class Meta:
        ordering = ["updated_at"]
        verbose_name_plural = "返信"


class Images(models.Model):
    image = models.ImageField(upload_to="image/")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.created_at)

    class Meta:
        ordering = ["-created_at"]
        verbose_name_plural = "画像"


class GoodInfo(models.Model):
    customUser = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, blank=True, null=True
    )
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return str(self.question.title)

    class Meta:
        verbose_name_plural = "高評価"

DollorBox/mathQA/views.py
import datetime
import json
import math
import os
import re
import secrets
import threading
from json import dumps

import pandas as pd
from django.contrib.auth import authenticate
from django.contrib.auth import login as dj_login
from django.contrib.auth import logout as dj_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password, make_password
from django.core.mail import send_mail
from django.db.models import Count, Q
from django.http import Http404, HttpResponse, HttpResponseRedirect, QueryDict
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from PIL import Image
from pykakasi import kakasi

try:
    from .email.local import *
except:
    from .email.product import *

from .models import *

# ログイン確認は別の方法がある

###################　注意　####################
###                                         ###
###　ajaxで変数を送るときはエスケープしてね　 ###
###                                         ###
###################　注意　####################

####--pykakasiの設定--####

kakasi = kakasi()
kakasi.setMode("H", "H")
kakasi.setMode("K", "H")
kakasi.setMode("J", "H")
# kakasi.setMode("r", "Hepburn")
kakasiconv = kakasi.getConverter()

####--ユーザー定義関数--####

# searchResultとdetailで使う


def createTitle(context):
    """
    本文から表示用のタイトルと残りの文章を取得する
    maxlength以下=>そのままタイトルだけ表示
    maxlengthより大きい=>数式が途切れないように最小値で
    """
    context = re.sub(
        r"\!\[.+?\]\([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.[\s\S]*?\)",
        "(画像)",
        context,
    )
    maxlength = 10
    if len(context) <= maxlength:
        return {
            "title": context,
            "leftcontext": "",
        }
    reg = r"(\\begin\{.*?\}[\s\S]*?\\end\{.*?\}|\$\$[\s\S]*?\$\$|\\\[[\s\S]*?\\\]|\$[\s\S]*?\$|\\\([\s\S]*?\\\))"
    part_sentence = [len(i) for i in re.split(reg, context) if i]
    separeteNum = 0
    startIsmath = bool(re.match(reg, context))
    for i, part in enumerate(part_sentence):
        separeteNum += part
        if separeteNum > maxlength:
            if startIsmath:
                separeteNum = separeteNum if i % 2 == 0 else maxlength
            else:
                separeteNum = maxlength if i % 2 == 0 else separeteNum
            break
    return {"title": context[:separeteNum], "leftcontext": context[separeteNum:]}


def __CreateContextData___(request, questions):
    Data = {}
    # PVランキング
    pvRanking = Question.objects.order_by("cntBrowsed").reverse()[:10]
    for pv in pvRanking:
        pv.title = createTitle(pv.contents)["title"]
    Data["pvRanking"] = pvRanking
    # 注目のランキング
    attentionRanking = (
        Question.objects.annotate(numberAnswer=Count("answer"))
        .order_by("numberAnswer", "updated_at")
        .reverse()[:10]
    )
    ats = []
    for at in attentionRanking:
        at.title = createTitle(at.contents)["title"]
    Data["attentionRanking"] = attentionRanking
    # 未解決の質問
    unsolveds = Question.objects.filter(bestAnswer=None)[:10]
    for uns in unsolveds:
        uns.title = createTitle(uns.contents)["title"]
    Data["unsolveds"] = unsolveds
    # ユーザの回答数ランキング
    numAnsRanking = (
        CustomUser.objects.annotate(ansCountByUser=Count("answer"))
        .order_by("ansCountByUser")
        .reverse()[:10]
    )
    Data["userAnsCountRanking"] = numAnsRanking
    return Data


def getBasicContectData(data):
    """__CreateContextData__から受け取ったデータから、基本的なページで使う情報を辞書にして返却する。
       基本的なページで使う情報とは、主にサイドバーに表示される情報であり、メインコンテンツによって左右されないものである。

    Args:
        data (dict): __CreateContextData___の返り値

    Returns:
        dict: 基本的なページで使う情報を返される。
    """
    context = {
        "userAnsCountRanking": data["userAnsCountRanking"],
        "unsolveds": data["unsolveds"],
        "pvRanking": data["pvRanking"],
        "attentionRanking": data["attentionRanking"],
    }
    return context


def resizeImg(path, minLength):
    """画像の比率をそのままに、特定のサイズにリサイズして上書き保存する。対応してない拡張子の場合はエラーを出す。

    Args:
        path (string): リサイズしたい画像までのパス。基準がmanage.pyであることに注意。view.pyではない。
        minLength (int): 短辺のサイズ(単位: px)
    """
    try:
        img = Image.open(path)
        w = img.width
        h = img.height
        if w > h:
            img = img.resize((int(minLength * w / h), minLength))
        else:
            img = img.resize((minLength, int(minLength * h / w)))
        main, ext = os.path.splitext(path)
        img.save(main + ext)
    except OSError as e:
        print("処理できない拡張子の可能性があります。")
        print(e)
    except Exception as e:
        print(e)


def async_send_email(subject, msg, from_email, recipient_list):
    if ALLOWED_SEND_EMAIL:
        send_mail(subject, msg, from_email, recipient_list)


####--ここから下はviews--####


# ホームページ
def index(request):
    if request.session.get("used-email"):
        return redirect("mathQA:user")
    context = {}
    questions = Question.objects.all()
    start = 0
    pagenum = 10
    imgmarkdown = r"\!\[.+?\]\([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|jpeg|gif|png|bmp)\)"
    questionSet = []
    for question in questions[start : start + pagenum]:
        content = question.contents
        content = re.sub(imgmarkdown, "(画像)", content)
        # if len(content) >= 50:
        #     content = content[:50] + "..."
        questionSet.append(
            {
                "question": question,
                "content": content,
            }
        )
    Data = __CreateContextData___(request, questions)
    context = getBasicContectData(Data)
    context.update(
        {
            "start": start + 1,
            "matomeNum": math.ceil(len(questions) / pagenum),
            "questionSet": questionSet,
            "tag": None,
        }
    )
    return render(request, "mathQA/searchResult.html", context)


# 工事中のページ
def undone(request):
    questions = Question.objects.all()
    Data = __CreateContextData___(request, questions)
    context = getBasicContectData(Data)
    return render(request, "mathQA/undone.html", context)


# プライバシーポリシー
def privacy_policy(request):
    questions = Question.objects.all()
    Data = __CreateContextData___(request, questions)
    context = getBasicContectData(Data)
    return render(request, "mathQA/privacy_policy.html", context)


# 利用規約
def terms_of_service(request):
    questions = Question.objects.all()
    Data = __CreateContextData___(request, questions)
    context = getBasicContectData(Data)
    return render(request, "mathQA/terms_of_service.html", context)


# ご意見
def opinionaire(request):
    questions = Question.objects.all()
    Data = __CreateContextData___(request, questions)
    context = getBasicContectData(Data)
    return render(request, "mathQA/opinionaire.html", context)


# チュートリアル
def tutorial(request):
    questions = Question.objects.all()
    Data = __CreateContextData___(request, questions)
    context = getBasicContectData(Data)
    return render(request, "mathQA/tutorial.html", context)


# タグの追加要望
def adding_tag_request(request):
    questions = Question.objects.all()
    Data = __CreateContextData___(request, questions)
    context = getBasicContectData(Data)
    return render(request, "mathQA/adding_tag_request.html", context)


# 登録
def register(request):
    context = {}
    if request.method == "POST":
        dic = QueryDict(request.body, encoding="utf-8")
        userName = dic.get("userName")
        email = dic.get("email")
        password = dic.get("password")
        if not (userName == "") and not (password == "") and not (email == ""):
            if CustomUser.objects.filter(username=userName).exists():
                res = dumps(
                    {
                        "status": "UserNameOverlap",
                        "msg": "ごめんなさいm(_ _)m そのユーザネームは既に使われています。",
                    }
                )
            elif CustomUser.objects.filter(email=email).exists():
                res = dumps(
                    {
                        "status": "EmailOverlap",
                        "msg": "ごめんなさいm(_ _)m そのメールアドレスは既に使われています。",
                    }
                )
            elif not re.match(
                r"^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$",
                email,
            ):
                res = dumps(
                    {
                        "status": "EmailNotCorrect",
                        "msg": "ごめんなさいm(_ _)m そのメールアドレスは正しくありません。",
                    }
                )
            else:
                token = secrets.token_hex()
                token_hash = make_password(token)
                info = CustomUser.objects.create_user(
                    username=userName,
                    email=email,
                    password=password,
                    emailtoken=Token.objects.create(token=token_hash),
                )
                info.save()

                user = authenticate(request, username=userName, password=password)
                dj_login(request, user)
                threading.Thread(
                    target=async_send_email, args=RegisterMessage(info, token, request)
                ).start()
                res = dumps({"status": 0, "msg": "", "redirect": "/"})
        else:
            res = dumps({"status": "InputLack", "msg": "入力が不足しています。(._.)"})
        return HttpResponse(res, content_type="application/json")
    else:
        return render(request, "mathQA/register.html", context)


def logout(request):
    try:
        dj_logout(request)
    except Exception:
        pass
    context = {"msg": ""}
    return redirect("/login/")


def login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("mathQA:user"))
    # バリデーションチェックはもっといい方法があるかも
    if request.method == "POST":
        dic = QueryDict(request.body, encoding="utf-8")
        userNameOrEmail = dic.get("userNameOrEmail")
        password = dic.get("password")

DollorBox/mathQA/templates/mathQA/layouts/base.html
{% load static %}
{% load md5url %}
<!DOCTYPE html>
<html lang="ja">

{% if request.path == '/' %}

<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">
  {% else %}

  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
    {% endif %}
    <script data-ad-client="ca-pub-2518715263291352" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-179039107-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() { dataLayer.push(arguments); }
      gtag('js', new Date());
      gtag('config', 'UA-179039107-1');
    </script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#1C5D7E">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta property="og:site_name" content="マスネット">
    <meta property="og:image" content="https://mathnet.biz/static/img/sns-share-logo.png">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@mathnet8">
    <meta name="google-site-verification" content="0JoNugADDaMVhF6vkzYFAPfarWBi4sR6G50ZN6IN8Cc" />
    {% block level-head %}{% endblock %}
    <title>マスネット | {% block tab-title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% md5url 'css/style.css' %}">
    <link rel="icon" href="{% md5url 'img/favicon.ico' %}">
    <link rel="stylesheet preload" href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap">
    <link rel="stylesheet preload" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet preload" href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.3.1/fuse.min.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    {% if request.get_host == 'mathnet.biz' %}
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>
    {% else %}
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    {% endif %}
    <script>
      MathJax = {
        tex: {
          inlineMath: [['$', '$'], ['\\(', '\\)']],
          processEscapes: true,
          autoload: {
            color: [],
            colorV2: ['color']
          },
          packages: { '[+]': ['noerrors'] }
        },
        chtml: {
          matchFontHeight: false,
          displayAlign: "left",
          displayIndent: "1em"
        },
        loader: {
          load: ['[tex]/noerrors']
        }
      };
    </script>
    <script defer id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <script defer src="{% md5url 'js/common.js' %}"></script>
  </head>

<body id="{% block body_id %}{% endblock %}" class="body  {% block body_class %}basic_body{% endblock %}">
  {% block l-body %}
  <header class="l-header header">
    <div class="header-logo">
      <a href="{% url 'mathQA:index' %}">
        <img src="{% md5url 'img/header-logo.png' %}" alt="マスネットロゴ">
      </a>
    </div>
    {% comment %} <input type="text" class="searchBox" placeholder="質問を検索">
    <button class="searchBtn">
      <span class="material-icons searchBox-icon">search</span>
    </button> {% endcomment %}
    <a class="goToQuestionBtn" href="{% url 'mathQA:writeQ' %}">
      <span class="material-icons">create</span>
      <span>質問する</span>
    </a>
    {% block header-right_space %}
    {% if not user.is_authenticated %}
    <a class="header-btn" href="{% url 'mathQA:login' %}">ログイン</a>
    <a class="header-btn header-registerBtn" href="{% url 'mathQA:register' %}">新規登録</a>
    {% else %}
    <div class="header-icon">
      <a href="{% url 'mathQA:user' %}"><img src="{{ MEDIA_URL }}{{ user.icon }}" alt="マイアイコン"></a>
    </div>
    {% endif %}
    <div id="js-ham-btn" class="header-ham"><span id="js-ham-icon" class="material-icons">menu_open</span></div>
    {% endblock header-right_space %}
  </header>
  <div class="l-header-Bg header-Bg"></div>

  {% comment %} PC版で画面下に固定サれているやつ {% endcomment %}
  {% block fixer %}
  <div class="l-fixer fixer">
    <p>
      <a href="{% url 'mathQA:opinionaire' %}" target="new" rel="noopener">ご意見を<br>下さい。</a>
    </p>
  </div>
  {% endblock fixer %}

  {% comment %} モバイル版で画面下に固定されているやつ {% endcomment %}

  {% block level-body_tag %}{% endblock %}

  {% block nav %}
  <div class="l-nav nav">
    <nav class="">
      <div class="nav-topic_path">
        {% block nav-now %}{% endblock %}
      </div>
      <div class="nav-title_path">
        <a href="{% url 'mathQA:index' %}"><span class="material-icons">home</span> ホーム</a>
        <a href="{% url 'mathQA:writeQ' %}"><span class="material-icons">create</span> 質問する</a>
        <a href="{% url 'mathQA:user' %}"><span class="material-icons">account_circle</span> マイアカウント</a>
        <a href="{% url 'mathQA:adding_tag_request' %}"><span class="material-icons">tag</span> タグ追加希望</a>
      </div>
      <div class="account-box-sp">
        {% if not user.is_authenticated %}
        <a class="account-sp" href="{% url 'mathQA:login' %}">ログイン</a>
        <a class="account-sp" href="{% url 'mathQA:register' %}">新規登録</a>
        {% else %}
        <div class="account-sp account-sp-img">
          <a href="{% url 'mathQA:user' %}"><img src="{{ MEDIA_URL }}{{ user.icon }}" alt="マイアイコン"></a>
        </div>
        {% endif %}
      </div>
    </nav>
  </div>
  {% endblock nav %}

  {% block l_sidebar %}
  <div class="l-l_sidebar l_sidebar">
    {% comment %} <div class="side_rank">
      <div class="side_rank-title">
        <p>回答数ランキング</p>
      </div>
      {% for user_ in userAnsCountRanking %}
      <div class="side_rank-row">
        <div class="row-user_icon"><img src="{{ MEDIA_URL }}{{ user_.icon }}" alt=""></div>
        <div class="row-user_name">{{ user_.username }}</div>
        <div class="row-ans_count">{{ user_.ansCountByUser }} 回</div>
      </div>
      {% endfor %}
    </div> {% endcomment %}
  </div>
  {% endblock l_sidebar %}

  <article class="l-main main">
    {% block main %}{% endblock main %}
  </article>

  {% block r_sidebar %}
  <article class="l-r_sidebar">
    <section class="relation_questions">
      <h2>未解決の疑問</h2>
      <div class="relation_questions-list">
        {% for unsolved in unsolveds %}
        <div class="r_sidevar-question_link"><a href="{% url 'mathQA:detail' unsolved.id %}">{{ unsolved.title }}</a>
        </div>
        {% endfor %}
      </div>
    </section>

    <section class="relation_questions">
      <h2>注目の疑問</h2>
      <div class="relation_questions-list">
        {% for attention in attentionRanking %}
        <div class="r_sidevar-question_link"><a href="{% url 'mathQA:detail' attention.id %}">{{ attention.title }}</a>
        </div>
        {% endfor %}
      </div>
    </section>

    <section class="relation_questions">
      <h2>閲覧数ランキング</h2>
      <div class="relation_questions-list">
        {% for pv in pvRanking %}
        <div class="r_sidevar-question_link"><a href="{% url 'mathQA:detail' pv.id %}">{{ pv.title }}</a></div>
        {% endfor %}
      </div>
    </section>
  </article>
  {% endblock r_sidebar %}

  {% block footer %}
  <footer class="l-footer footer">
    <div class="l-footer-body footer-body">
      <div class="footer-section">
        <img src="{% md5url 'img/header-logo.png' %}" alt="マスネットロゴ">
        <p>数学のためのQ&Aサイト</p>
      </div>
      <a class="footer-privacy_policy" href="{% url 'mathQA:privacy_policy' %}">プライバシーポリシー</a>
      <p class="footer-text">お問い合わせ：mathnet.jp@gmail.com</p>
      <p class="footer-text">&copy; 2020 h-kawa, k-saki</p>
    </div>
  </footer>
  {% endblock footer %}

  {% block footbar %}
  <div class="l-footbar footbar">
    <div class="footbar-menu {% if request.path == '/' %}footbar-menu--selected{% endif %}">
      <a href="{% url 'mathQA:index' %}">
        <div class="footbar-icon"><span class="material-icons">home</span></div>
        <div class="footbar-text">ホーム</div>
      </a>
    </div>
    <div class="footbar-menu {% if request.path == '/writeQ/' %}footbar-menu--selected{% endif %}">
      <a href="{% url 'mathQA:writeQ' %}">
        <div class="footbar-icon"><span class="material-icons">create</span></div>
        <div class="footbar-text">質問</div>
      </a>
    </div>
    <div class="footbar-menu {% if request.path == '/opinionaire/' %}footbar-menu--selected{% endif %}">
      <a href="{% url 'mathQA:opinionaire' %}">
        <div class="footbar-icon"><span class="material-icons">message</span></div>
        <div class="footbar-text">アドバイス</div>
      </a>
    </div>
    {% if user.is_authenticated %}
    <div class="footbar-menu {% if request.path == '/user/' %}footbar-menu--selected{% endif %}">
      <a href="{% url 'mathQA:user' %}">
        <div class="footbar-icon footbar-icon-user_icon"><img src="{{ MEDIA_URL }}{{ user.icon }}" alt="マイアイコン"></div>
        <div class="footbar-text">マイアカウント</div>
      </a>
    </div>
    {% endif %}
  </div>
  {% endblock footbar %}

  {% endblock l-body %}

  {% block js-end-load %}{% endblock %}

</body>

</html>

DollorBox/mathQA/templates/mathQA/layouts/skeleton.html
{% extends "mathQA/layouts/base.html" %}
{% load static %}
{% load md5url %}

{# これはコメントです。 #}
{# このskelton.htmlに必要な要素を埋め込んで、各ページのhtmlを生成していきます。 #}

{# タブタイトル #}
{% block tab-title %}{% endblock %}

{% block header-right_space %}
{% endblock header-right_space %}

{% block l-body %}
{% endblock l-body %}

{# 【オプション】これはbodyタグの直下階層に設置したいものをいれます。 #}
{% block level-body_tag %}
{% endblock level-body_tag %}

  {# 左サイドバー全体 #}
  {% block nav %}
  {% endblock %}

    {# 左サイドバーの現在のパス（パンくず） #}
    {% block nav-now %}
    {% endblock %}

  {# メインコンテンツ #}
  {% block main %}
  {% endblock main %}

  {# 【オプション】これはbase.htmlで右サイドバーを囲っています。つまり、右サイドバーを消したいときはここを空白にしてください。 #}
  {% block r_sidebar %}
  {% endblock r_sidebar %}

  {% block fixer %}
  {% endblock fixer %}

{# 【オプション】bodyタグ直前で読み込みたいjsファイルです。 #}
{% block js-end-load %}
{% endblock %}