DollorBox/DollorBox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap


# サイトマップ
from .sitemaps import (
    PostSitemap,
    StaticViewSitemap,
)

sitemaps = {
    'post': PostSitemap,
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('kanrisya987123/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('', include('mathQA.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap')
]

DollorBox/mathQA/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = "mathQA"
urlpatterns = [
    path("", views.index, name="index"),
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("user/", views.user, name="user"),
    path("writeQ/", views.writeQ, name="writeQ"),
    path("detail/<int:questionID>/", views.detail, name="detail"),
    path("searchResult/<int:start>/", views.searchResult, name="searchResult"),
    path("undone/", views.undone, name="undone"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("terms_of_service/", views.terms_of_service, name="terms_of_service"),
    path("tutorial/", views.tutorial, name="tutorial"),
    path("adding_tag_request/", views.adding_tag_request, name="adding_tag_request"),
    path(
        "adding_tag_request_post/",
        views.adding_tag_request_post,
        name="adding_tag_request_post",
    ),
    path("opinionaire/", views.opinionaire, name="opinionaire"),
    path("img_post/", views.img_post, name="img_post"),
    path("good_post/", views.good_post, name="good_post"),
    path(
        "settings_post/<str:section>/<str:item>/",
        views.settings_post,
        name="settings_post",
    ),
    path("bestans_post/<int:questionID>/", views.bestans_post, name="bestans_post"),
    path("tags/<str:tag>/<int:start>/", views.searchResult, name="tagSearchResult"),
    path("auth-complete/<str:token>/", views.auth_complete, name="auth-complete"),
    path("landingpage/", views.LandingPage, name="landingpage"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DollorBox/mathQA/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser


class Token(models.Model):
    token = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name_plural = "トークン"


class CustomUser(AbstractUser):
    icon = models.ImageField(upload_to="icon/", default="system_init/firsticon.jpg")
    verified = models.BooleanField(default=False)
    emailtoken = models.OneToOneField(
        Token, on_delete=models.CASCADE, null=True, blank=True
    )

    class Meta:
        verbose_name_plural = "カスタムユーザー"


class QuestionTag(models.Model):
    tagName = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.tagName)

    class Meta:
        ordering = ["-created_at"]
        verbose_name_plural = "使用可能なタグ(追加可能)"


class Question(models.Model):
    title = models.CharField(max_length=200, null=True)
    customUser = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    contents = models.TextField()
    bestAnswer = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(default=timezone.now)
    cntBrowsed = models.PositiveIntegerField(default=0)
    tags = models.ManyToManyField(QuestionTag)

    def __str__(self):
        return self.contents[:15]

    class Meta:
        ordering = ["-updated_at"]
        verbose_name_plural = "質問"


class Answer(models.Model):
    customUser = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    contents = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.question.title

    class Meta:
        ordering = ["updated_at"]
        verbose_name_plural = "解答"


class Reply(models.Model):
    customUser = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    contents = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.answer.question.title

    class Meta:
        ordering = ["updated_at"]
        verbose_name_plural = "返信"


class Images(models.Model):
    image = models.ImageField(upload_to="image/")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.created_at)

    class Meta:
        ordering = ["-created_at"]
        verbose_name_plural = "画像"


class GoodInfo(models.Model):
    customUser = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, blank=True, null=True
    )
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return str(self.question.title)

    class Meta:
        verbose_name_plural = "高評価"

DollorBox/mathQA/views.py
import datetime
import json
import math
import os
import re
import secrets
import threading
from json import dumps

import pandas as pd
from django.contrib.auth import authenticate
from django.contrib.auth import login as dj_login
from django.contrib.auth import logout as dj_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password, make_password
from django.core.mail import send_mail
from django.db.models import Count, Q
from django.http import Http404, HttpResponse, HttpResponseRedirect, QueryDict
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from PIL import Image
from pykakasi import kakasi

try:
    from .email.local import *
except:
    from .email.product import *

from .models import *

# ログイン確認は別の方法がある

###################　注意　####################
###                                         ###
###　ajaxで変数を送るときはエスケープしてね　 ###
###                                         ###
###################　注意　####################

####--pykakasiの設定--####

kakasi = kakasi()
kakasi.setMode("H", "H")
kakasi.setMode("K", "H")
kakasi.setMode("J", "H")
# kakasi.setMode("r", "Hepburn")
kakasiconv = kakasi.getConverter()

####--ユーザー定義関数--####

# searchResultとdetailで使う


def createTitle(context):
    """
    本文から表示用のタイトルと残りの文章を取得する
    maxlength以下=>そのままタイトルだけ表示
    maxlengthより大きい=>数式が途切れないように最小値で
    """
    context = re.sub(
        r"\!\[.+?\]\([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.[\s\S]*?\)",
        "(画像)",
        context,
    )
    maxlength = 10
    if len(context) <= maxlength:
        return {
            "title": context,
            "leftcontext": "",
        }
    reg = r"(\\begin\{.*?\}[\s\S]*?\\end\{.*?\}|\$\$[\s\S]*?\$\$|\\\[[\s\S]*?\\\]|\$[\s\S]*?\$|\\\([\s\S]*?\\\))"
    part_sentence = [len(i) for i in re.split(reg, context) if i]
    separeteNum = 0
    startIsmath = bool(re.match(reg, context))
    for i, part in enumerate(part_sentence):
        separeteNum += part
        if separeteNum > maxlength:
            if startIsmath:
                separeteNum = separeteNum if i % 2 == 0 else maxlength
            else:
                separeteNum = maxlength if i % 2 == 0 else separeteNum
            break
    return {"title": context[:separeteNum], "leftcontext": context[separeteNum:]}


def __CreateContextData___(request, questions):
    Data = {}
    # PVランキング
    pvRanking = Question.objects.order_by("cntBrowsed").reverse()[:10]
    for pv in pvRanking:
        pv.title = createTitle(pv.contents)["title"]
    Data["pvRanking"] = pvRanking
    # 注目のランキング
    attentionRanking = (
        Question.objects.annotate(numberAnswer=Count("answer"))
        .order_by("numberAnswer", "updated_at")
        .reverse()[:10]
    )
    ats = []
    for at in attentionRanking:
        at.title = createTitle(at.contents)["title"]
    Data["attentionRanking"] = attentionRanking
    # 未解決の質問
    unsolveds = Question.objects.filter(bestAnswer=None)[:10]
    for uns in unsolveds:
        uns.title = createTitle(uns.contents)["title"]
    Data["unsolveds"] = unsolveds
    # ユーザの回答数ランキング
    numAnsRanking = (
        CustomUser.objects.annotate(ansCountByUser=Count("answer"))
        .order_by("ansCountByUser")
        .reverse()[:10]
    )
    Data["userAnsCountRanking"] = numAnsRanking
    return Data


def getBasicContectData(data):
    """__CreateContextData__から受け取ったデータから、基本的なページで使う情報を辞書にして返却する。
       基本的なページで使う情報とは、主にサイドバーに表示される情報であり、メインコンテンツによって左右されないものである。

    Args:
        data (dict): __CreateContextData___の返り値

    Returns:
        dict: 基本的なページで使う情報を返される。
    """
    context = {
        "userAnsCountRanking": data["userAnsCountRanking"],
        "unsolveds": data["unsolveds"],
        "pvRanking": data["pvRanking"],
        "attentionRanking": data["attentionRanking"],
    }
    return context


def resizeImg(path, minLength):
    """画像の比率をそのままに、特定のサイズにリサイズして上書き保存する。対応してない拡張子の場合はエラーを出す。

    Args:
        path (string): リサイズしたい画像までのパス。基準がmanage.pyであることに注意。view.pyではない。
        minLength (int): 短辺のサイズ(単位: px)
    """
    try:
        img = Image.open(path)
        w = img.width
        h = img.height
        if w > h:
            img = img.resize((int(minLength * w / h), minLength))
        else:
            img = img.resize((minLength, int(minLength * h / w)))
        main, ext = os.path.splitext(path)
        img.save(main + ext)
    except OSError as e:
        print("処理できない拡張子の可能性があります。")
        print(e)
    except Exception as e:
        print(e)


def async_send_email(subject, msg, from_email, recipient_list):
    if ALLOWED_SEND_EMAIL:
        send_mail(subject, msg, from_email, recipient_list)


####--ここから下はviews--####


# ホームページ
def index(request):
    if request.session.get("used-email"):
        return redirect("mathQA:user")
    context = {}
    questions = Question.objects.all()
    start = 0
    pagenum = 10
    imgmarkdown = r"\!\[.+?\]\([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|jpeg|gif|png|bmp)\)"
    questionSet = []
    for question in questions[start : start + pagenum]:
        content = question.contents
        content = re.sub(imgmarkdown, "(画像)", content)
        # if len(content) >= 50:
        #     content = content[:50] + "..."
        questionSet.append(
            {
                "question": question,
                "content": content,
            }
        )
    Data = __CreateContextData___(request, questions)
    context = getBasicContectData(Data)
    context.update(
        {
            "start": start + 1,
            "matomeNum": math.ceil(len(questions) / pagenum),
            "questionSet": questionSet,
            "tag": None,
        }
    )
    return render(request, "mathQA/searchResult.html", context)


# 工事中のページ
def undone(request):
    questions = Question.objects.all()
    Data = __CreateContextData___(request, questions)
    context = getBasicContectData(Data)
    return render(request, "mathQA/undone.html", context)


# プライバシーポリシー
def privacy_policy(request):
    questions = Question.objects.all()
    Data = __CreateContextData___(request, questions)
    context = getBasicContectData(Data)
    return render(request, "mathQA/privacy_policy.html", context)


# 利用規約
def terms_of_service(request):
    questions = Question.objects.all()
    Data = __CreateContextData___(request, questions)
    context = getBasicContectData(Data)
    return render(request, "mathQA/terms_of_service.html", context)


# ご意見
def opinionaire(request):
    questions = Question.objects.all()
    Data = __CreateContextData___(request, questions)
    context = getBasicContectData(Data)
    return render(request, "mathQA/opinionaire.html", context)


# チュートリアル
def tutorial(request):
    questions = Question.objects.all()
    Data = __CreateContextData___(request, questions)
    context = getBasicContectData(Data)
    return render(request, "mathQA/tutorial.html", context)


# タグの追加要望
def adding_tag_request(request):
    questions = Question.objects.all()
    Data = __CreateContextData___(request, questions)
    context = getBasicContectData(Data)
    return render(request, "mathQA/adding_tag_request.html", context)


# 登録
def register(request):
    context = {}
    if request.method == "POST":
        dic = QueryDict(request.body, encoding="utf-8")
        userName = dic.get("userName")
        email = dic.get("email")
        password = dic.get("password")
        if not (userName == "") and not (password == "") and not (email == ""):
            if CustomUser.objects.filter(username=userName).exists():
                res = dumps(
                    {
                        "status": "UserNameOverlap",
                        "msg": "ごめんなさいm(_ _)m そのユーザネームは既に使われています。",
                    }
                )
            elif CustomUser.objects.filter(email=email).exists():
                res = dumps(
                    {
                        "status": "EmailOverlap",
                        "msg": "ごめんなさいm(_ _)m そのメールアドレスは既に使われています。",
                    }
                )
            elif not re.match(
                r"^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$",
                email,
            ):
                res = dumps(
                    {
                        "status": "EmailNotCorrect",
                        "msg": "ごめんなさいm(_ _)m そのメールアドレスは正しくありません。",
                    }
                )
            else:
                token = secrets.token_hex()
                token_hash = make_password(token)
                info = CustomUser.objects.create_user(
                    username=userName,
                    email=email,
                    password=password,
                    emailtoken=Token.objects.create(token=token_hash),
                )
                info.save()

                user = authenticate(request, username=userName, password=password)
                dj_login(request, user)
                threading.Thread(
                    target=async_send_email, args=RegisterMessage(info, token, request)
                ).start()
                res = dumps({"status": 0, "msg": "", "redirect": "/"})
        else:
            res = dumps({"status": "InputLack", "msg": "入力が不足しています。(._.)"})
        return HttpResponse(res, content_type="application/json")
    else:
        return render(request, "mathQA/register.html", context)


def logout(request):
    try:
        dj_logout(request)
    except Exception:
        pass
    context = {"msg": ""}
    return redirect("/login/")


def login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("mathQA:user"))
    # バリデーションチェックはもっといい方法があるかも
    if request.method == "POST":
        dic = QueryDict(request.body, encoding="utf-8")
        userNameOrEmail = dic.get("userNameOrEmail")
        password = dic.get("password")

DollorBox/mathQA/templates/mathQA/authtoken.html
{% extends "mathQA/layouts/base.html" %}
{% load static %}
{% load md5url %}

{% block tab-title %}メール認証{% endblock %}

{% block main %}
{{ user.email }}の{{ msg }}
{% endblock main %}

DollorBox/mathQA/templates/mathQA/index.html
{% load static %}
{% load md5url %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>mathQA | トップ</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body>
  <a href="{% url 'mathQA:writeQ' %}">質問ページ</a><br>
  <a href="{% url 'mathQA:searchResult' 1 %}">検索結果</a><br>
  <a href="{% url 'mathQA:login' %}">ログイン</a><br>
  <a href="{% url 'mathQA:logout' %}">ログアウト</a><br>
  <a href="{% url 'mathQA:user' %}">ユーザーページ</a>
  <script defer src="{% md5url 'js/common.js' %}"></script>
  <script defer src="{% md5url 'js/index.js' %}"></script>
</body>

</html>

DollorBox/mathQA/templates/mathQA/sample.html
{% load static %}
{% load md5url %}

<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="theme-color" content="#1C5D7E">
  <title>マスネット | 質問投稿</title>
  <link rel="icon" href="{% md5url 'img/favicon.ico' %}">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="{% md5url 'css/style.css' %}">
  <script>
    MathJax = {
      tex: {
        inlineMath: [['$', '$'], ['\\(', '\\)']],
        processEscapes: true,
        autoload: {
          color: [],
          colorV2: ['color']
        },
        packages: { '[+]': ['noerrors'] }
      },
      chtml: {
        matchFontHeight: false,
        displayAlign: "left",
        displayIndent: "1em",
      },
      loader: {
        load: ['[tex]/noerrors']
      },
      svg: {
        fontCache: 'global'
      }
    };

  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
</head>

<body>
  <header class="l-header header">
    <div class="header-logo">
      <a href="{% url 'mathQA:index' %}">
        <img src="{% md5url 'img/header-logo.png' %}" alt="マスネットロゴ">
      </a>
    </div>
    <input type="text" class="searchBox" placeholder="質問を検索">
    <button class="searchBtn">
      <span class="material-icons searchBox-icon">search</span>
    </button>
    <a class="goToQuestionBtn" href="{% url 'mathQA:writeQ' %}">疑問を解決する</a>
    {% if status == 'guest' %}
    <a class="header-btn" href="{% url 'mathQA:login' %}">ログイン</a>
    <a class="header-btn header-registerBtn" href="{% url 'mathQA:register' %}">新規登録</a>
    {% else %}
    <div class="header-icon">
      <a href="{% url 'mathQA:user' %}"><img src="{{ MEDIA_URL }}{{ userData.icon }}" alt="マイアイコン"></a>
    </div>
    {% endif %}
  </header>
  <div class="l-header-Bg"></div>

  <div class="l-body">
    <nav class="l-l_sidebar">
      <div class="nav-topic_path">
        <a href="{% url 'mathQA:index' %}">ホーム</a> >
        <a href="{% url 'mathQA:searchResult' 1 %}">質問投稿</a>
      </div>
      <div class="nav-title_path">
        <a href="{% url 'mathQA:index' %}">ホーム</a>
        <a href="{% url 'mathQA:writeQ' %}">質問する</a>
        <a href="{% url 'mathQA:undone' %}">タグ検索</a>
        <a href="{% url 'mathQA:undone' %}">ユーザ検索</a>
        <a href="{% url 'mathQA:user' %}">設定</a>
      </div>
    </nav>

    <article class="l-main">
      <!-- ここから -->
      <section class="l-post">
        <p class="ermsg"></p>
        <div class="l-right_post_box">
          {% csrf_token %}
          <div class="mathForm" data-json='{"post_url": "/writeQ/"}'>
            <div class="textara_title">
              <input class="js-question-title oneline_input question-title" type="text" placeholder="質問タイトルを入力"
                name="title" autocomplete="off">
            </div>
            <div class="mathForm_btns">
              <input class="normal_btn js_convertToFormula_inline" type="button" value="inline">
              <input class="normal_btn js_convertToFormula_display" type="button" value="display">
              <input class="normal_btn js_convertToFormula_frac" type="button" value="frac">
              <input class="normal_btn js_convertToFormula_sqrt" type="button" value="sqrt">
              <input class="normal_btn js_convertToFormula_bottom" type="button" value="bottom">
              <input class="normal_btn js_convertToFormula_sigma" type='button' value="sigma">
              <input class="normal_btn js_convertToFormula_tag" type="button" value="tag">
              <label class="normal_btn file_btn">
                画像を挿入
                <input class="file_input js_convertToFormula_pic" type="file">
              </label>
            </div>
            <textarea name="text" class="mathForm_input post-textarea" placeholder="質問を入力"></textarea>
            <div class="mathForm_box post-textarea post-preview">
              <p class="mathForm_output"></p>
            </div>
          </div>
        </div>
      </section>
      <section class="l-post">
        <p class="ermsg"></p>
        <div class="l-right_post_box">
          {% csrf_token %}
          <div class="mathForm" data-json='{"post_url": "/writeQ/"}'>
            <div class="textara_title">
              <input class="js-question-title oneline_input question-title" type="text" placeholder="質問タイトルを入力"
                name="title" autocomplete="off">
            </div>
            <div class="mathForm_btns">
              <input class="normal_btn js_convertToFormula_inline" type="button" value="inline">
              <input class="normal_btn js_convertToFormula_display" type="button" value="display">
              <input class="normal_btn js_convertToFormula_frac" type="button" value="frac">
              <input class="normal_btn js_convertToFormula_sqrt" type="button" value="sqrt">
              <input class="normal_btn js_convertToFormula_bottom" type="button" value="bottom">
              <input class="normal_btn js_convertToFormula_sigma" type='button' value="sigma">
              <input class="normal_btn js_convertToFormula_tag" type="button" value="tag">
              <label class="normal_btn file_btn">
                画像を挿入
                <input class="file_input js_convertToFormula_pic" type="file">
              </label>
            </div>
            <textarea name="text" class="mathForm_input post-textarea" placeholder="質問を入力"></textarea>
            <div class="mathForm_box post-textarea post-preview">
              <p class="mathForm_output"></p>
            </div>
          </div>
        </div>
      </section>

    </article>

  </div>

  <footer class="l-footer footer">
    フッダー なんか書く
  </footer>
  <script defer src="{% md5url 'js/common.js' %}"></script>
  <script defer src="{% md5url 'js/mathForm.js' %}"></script>
</body>

</html>

DollorBox/mathQA/templates/mathQA/searchResult.html
{% extends "mathQA/layouts/base.html" %}
{% load static %}
{% load md5url %}

{% block level-head %}
<meta property="og:url" content="https://mathnet.biz/">
<meta property="og:type" content="website">
<meta property="og:title" content="質問一覧">
<meta property="og:description" content="数学のためのQ&amp;Aサイト。数学好きが集まる、数学のなぜ？どうやって？を質問する場所。LaTeXで数式がキレイに書けます。">
{% endblock level-head %}

{% block tab-title %}ホーム{% endblock %}

{% block nav-now %}<a href="{% url 'mathQA:index'  %}">ホーム</a>{% endblock %}

{% block level-body_tag %}
{% if not user.verified and user.is_authenticated %}
<section class="l-popBg popBg">
  <div class="l-pop pop">
    <div class="close_btn">
      <span class="material-icons close_icon">close</span>
    </div>
    <div class="pop-title">
      <p>メールを確認してね</p>
    </div>
    <div class="pop-body">
      <p>{{ user.email }}にメールをお送りしました。ご確認下さいm(_ _)m</p>
    </div>
    <button id="pop-conf_btn" class="normal_btn pop-conf_btn">了解</button>
  </div>
</section>
{% endif %}
{% endblock level-body_tag %}

{% block main %}
{% for q in questionSet %}
<section class="l-list q-list">
  <div class="l-list-left">
    {% if q.question.bestAnswer %}
    <div class="list-q_stat list-q_stat--solved">
      <p>解決済</p>
    </div>
    {% else %}
    <div class="list-q_stat">
      <p>受付中</p>
    </div>
    {% endif %}
  </div>
  <div class="l-list-right">
    <div class="list-tag">
      {% for tag in q.question.tags.all %}
      <a href="{% url 'mathQA:tagSearchResult' tag 1  %}" class="list-tag-item"><span
          class="material-icons">tag</span>{{tag}}</a>
      {% endfor %}
    </div>
    <div class="list-content">
      <p>
        {{q.question.title}}
        {{q.content}}
      </p>
    </div>
    <a class="list-link" href="{% url 'mathQA:detail' q.question.id %}">質問を見る<span
        class=" material-icons">navigate_next</span></a>
    <div class="post-footer">
      <div class="post-footer-wrap">
        <div class="post-footer-item list-pv">
          <p>PV {{q.question.cntBrowsed}}</p>
        </div>
        <div class="post-footer-item list-evaluation">
          <p><span class="material-icons">favorite</span>{{q.question.goodinfo_set.all|length}}</p>
        </div>
        <div class="post-footer-item post-date">
          <p>{{q.question.updated_at|date:"Y/m/d"}}</p>
        </div>
        <div class="post-footer-item psot-time">
          <p>{{q.question.updated_at|date:"H:i"}}</p>
        </div>
      </div>
      <div class="post-footer-wrap">
        <div class="post-footer-item post-poster">
          <p>{{q.question.customUser.username}}</p>
        </div>
      </div>
      <div class="post-footer-wrap">
        <div class="post-footer-item post-poster_icon"><img src="{{MEDIA_URL}}{{q.question.customUser.icon}}"
            alt="投稿者アイコン">
        </div>
      </div>
    </div>
  </div>
</section>
{% endfor %}

<div class="l-range">
  {% with ''|center:matomeNum as range %}
  {% for _ in range %}
  {% if "/tags/" in request.path %}
  {% if start == forloop.counter %}
  <a class="range-box range-box--now"
    href="{% url 'mathQA:tagSearchResult' tag forloop.counter %}">{{forloop.counter}}</a>
  {% else %}
  <a class="range-box" href="{% url 'mathQA:tagSearchResult' tag forloop.counter %}">{{forloop.counter}}</a>
  {% endif %}
  {% else %}
  {% if start == forloop.counter %}
  <a class="range-box range-box--now" href="{% url 'mathQA:searchResult' forloop.counter %}">{{forloop.counter}}</a>
  {% else %}
  <a class="range-box" href="{% url 'mathQA:searchResult' forloop.counter %}">{{forloop.counter}}</a>
  {% endif %}
  {% endif %}
  {% endfor %}
  {% endwith %}
</div>
{% endblock main %}

{% block js-end-load %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"
  integrity="sha512-aUhL2xOCrpLEuGD5f6tgHbLYEXRpYZ8G5yD+WlFrXrPy2IrWBlu6bih5C9H6qGsgqnU6mgx6KtU8TreHpASprw=="
  crossorigin="anonymous"></script>
<script defer src="{% md5url 'js/searchResult.js' %}"></script>
<script>
  searchResult_isLogined = "{{ user.is_authenticated }}";
  searchResult_isVerified = "{{ user.verified }}";
</script>
{% endblock %}

DollorBox/mathQA/templates/mathQA/undone.html
{% extends "mathQA/layouts/base.html" %}
{% load static %}
{% load md5url %}

{% block tab-title %}開発中{% endblock %}

{% block nav-now %}
<a href="{% url 'mathQA:index' %}">ホーム</a> >
<a href="{% url 'mathQA:undone' %}">開発中</a>
{% endblock %}

{% block main %}
ごめんなさい。。。この機能は現在準備中です！ご期待を！
{% endblock main %}

{% block js-end-load %}
<script defer src="{% md5url 'js/mathForm.js' %}"></script>
{% endblock %}